# Generated by Django 5.2.6 on 2025-09-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_analista', models.CharField(max_length=50)),
                ('ul_loterica', models.CharField(max_length=11)),
                ('inc_chamado', models.IntegerField()),
                ('nome_tecnico', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_conclusao', models.TimeField()),
                ('tipo_chamado', models.CharField(max_length=20)),
                ('serial_sky2', models.IntegerField()),
                ('serial_sky2c', models.IntegerField()),
                ('produtiva', models.BooleanField(default=True)),
                ('senha', models.CharField(max_length=12)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
