# Generated by Django 4.2.24 on 2025-10-13 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados_planejados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamados_hoje', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AddField(
            model_name='chamados',
            name='status',
            field=models.CharField(default='opaaa', max_length=20),
        ),
    ]
