# Generated by Django 5.2.6 on 2025-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
