# Generated by Django 5.2.6 on 2025-09-24 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
