# Generated by Django 4.2.24 on 2025-10-14 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0002_chamados_planejados_chamados_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='data_planejada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='data_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamados',
            name='origem_planilha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamados',
            name='status_legacy',
            field=models.CharField(default='opaaa', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='ID_chamado',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='conclusao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='nome_analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='nome_tecnico',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='senha',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='tipo_atividade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='total_horas',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
