# Generated by Django 5.2.6 on 2025-10-13 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_chamados_planejados_chamados_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados_andamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamados_planejados',
            name='chamados_hoje',
        ),
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(default='Em atendimento', max_length=20),
        ),
    ]
