# Generated by Django 5.2.6 on 2025-10-13 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_chamados_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados_planejados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamados_hoje', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
