# Generated by Django 5.2.6 on 2025-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_informations_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='produtiva',
            field=models.CharField(max_length=100),
        ),
    ]
