# Generated by Django 5.2.6 on 2025-09-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_informations_produtiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='data',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='hora_conclusao',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='nome_tecnico',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='produtiva',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='serial_sky2',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='serial_sky2c',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='tipo_chamado',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='ul_loterica',
        ),
    ]
