# Generated by Django 5.2.6 on 2025-10-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_chamados_planejados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(default='opa', max_length=20),
        ),
    ]
