# Generated by Django 4.2.24 on 2025-10-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_chamados_data_planejada_chamados_data_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamados',
            name='status_legacy',
        ),
    ]
