# Generated by Django 5.2.6 on 2025-09-24 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_informations_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_analista', models.CharField(max_length=50)),
                ('inc_chamado', models.IntegerField()),
                ('data', models.DateTimeField(default=datetime.date.today)),
                ('inicio', models.TimeField()),
                ('conclusao', models.TimeField()),
                ('total_horas', models.TimeField()),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Informations',
        ),
    ]
