# Generated by Django 4.2.24 on 2025-10-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_chamados_status_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('produtiva', 'Produtiva'), ('improdutiva', 'Improdutiva')], default='planejado', max_length=20),
        ),
    ]
