# Generated by Django 5.2.6 on 2025-10-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_chamados_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(default='opaaa', max_length=20),
        ),
    ]
