# Generated by Django 4.2.24 on 2025-10-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_chamados_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='ID_chamado',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
