# Generated by Django 5.2.6 on 2025-09-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_chamados_delete_informations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='inc_chamado',
            new_name='ID_chamado',
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='total_horas',
            field=models.TimeField(default='00:00'),
        ),
    ]
