# Generated by Django 5.2.6 on 2025-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_rename_inc_chamado_chamados_id_chamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='produtiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chamados',
            name='tecnico',
            field=models.CharField(default='OK', max_length=100),
        ),
    ]
