# Generated by Django 5.2.6 on 2025-10-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_chamados_id_chamado'),
    ]

    operations = [
    ]
