# Generated by Django 5.2.6 on 2025-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_chamados_produtiva_chamados_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='tecnico',
            field=models.CharField(max_length=30),
        ),
    ]
