# Generated by Django 4.2.25 on 2025-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20251016_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='total_horas',
            field=models.FloatField(blank=True, help_text='Total de horas em decimal (ex: 2.5 para 2h30min)', null=True),
        ),
    ]
