# Generated by Django 5.2.6 on 2025-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_chamados_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='observacao',
            field=models.TextField(default='digite aqui sua obsevação'),
        ),
    ]
