# Generated by Django 4.2.7 on 2025-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_chamados_total_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='previsto',
            field=models.DateField(blank=True, help_text='Data em que o chamado deve aparecer na tela', null=True),
        ),
    ]
