# Generated by Django 5.2.6 on 2025-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_chamados_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='observacao',
            field=models.TextField(),
        ),
    ]
