# Generated by Django 4.2.7 on 2025-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_chamados_previsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='data_planejada',
            field=models.DateField(blank=True, help_text='Data em que o chamado deve aparecer na tela', null=True),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='previsto',
            field=models.TimeField(blank=True, help_text='Horário previsto do chamado', null=True),
        ),
    ]
