# Generated by Django 5.2.6 on 2025-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_chamados_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='total_horas',
            field=models.TimeField(),
        ),
    ]
