# Generated by Django 5.2.6 on 2025-09-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_chamados_total_horas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='tecnico',
            new_name='nome_tecnico',
        ),
    ]
