# Generated by Django 5.2.6 on 2025-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_rename_tecnico_chamados_nome_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='tipo_atividade',
            field=models.CharField(choices=[('Manutenção', 'manutenção'), ('Migração', 'migração'), ('Remanejamento', 'remanejamento'), ('Mudança de indereço', 'mudança de indereço')], default='Manutenção', max_length=30),
        ),
    ]
