# Generated by Django 5.2.6 on 2025-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_alter_chamados_tipo_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='tipo_atividade',
            field=models.CharField(choices=[('Manutencao', 'manutencao'), ('Migracao', 'migracao'), ('Mudanca_endereco', 'mudanca_endereco'), ('Remanejamento', 'remanejamento')], max_length=30),
        ),
    ]
