# Generated by Django 5.2.6 on 2025-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_alter_chamados_tipo_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='tipo_atividade',
            field=models.CharField(max_length=30),
        ),
    ]
