# Generated by Django 5.2.6 on 2025-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_alter_chamados_nome_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='nome_analista',
            field=models.CharField(default='ok', max_length=30),
        ),
    ]
